### ISSUE TITLE
cl.el and defun*

### ISSUE THREAD

**Issue by csheaff** [kosh04/unicode-escape.el#5]
Hello, I am using this library as a dependency for `company-tabnine` with Emacs 30. It seems that `defun*` and `cl.el` has been phased out, as I got an error when trying to run the company package. I also have a warning about an unknown type `char-or-string` regarding the function `-escape-object`.

![image](https://user-images.githubusercontent.com/10719781/211168886-69875778-1e1a-445c-af53-3ae198ce0d72.png)

**Comment by kosh04** [comment]
Warning about `defun*` was resolved #3 
The other warnings will be modified at a later.

**Comment by csheaff** [comment]
Okay, thank you.
